python src/calibration_array_launch.py 1
python src/calibration_array_launch.py 2
python src/calibration_array_launch.py 3
python src/calibration_array_launch.py 4
python src/calibration_array_launch.py 5
python src/calibration_array_launch.py 6
python src/calibration_array_launch.py 7
python src/calibration_array_launch.py 8
python src/calibration_array_launch.py 9
python src/calibration_array_launch.py 10
python src/calibration_array_launch.py 11
python src/calibration_array_launch.py 12
python src/calibration_array_launch.py 13
python src/calibration_array_launch.py 14
python src/calibration_array_launch.py 15
python src/calibration_array_launch.py 16
python src/calibration_array_launch.py 17
python src/calibration_array_launch.py 18
python src/calibration_array_launch.py 19
python src/calibration_array_launch.py 20
python src/calibration_array_launch.py 21
python src/calibration_array_launch.py 22
python src/calibration_array_launch.py 23
python src/calibration_array_launch.py 24
python src/calibration_array_launch.py 25
python src/calibration_array_launch.py 26