python main_INIT_array_DEV.py     0
python main_INIT_array_DEV.py     1 
python main_INIT_array_DEV.py     2
python main_INIT_array_DEV.py     3
python main_INIT_array_DEV.py     4
python main_INIT_array_DEV.py     5
python main_INIT_array_DEV.py     6
python main_INIT_array_DEV.py     7
python main_INIT_array_DEV.py     8
python main_INIT_array_DEV.py     9
python main_INIT_array_DEV.py    10
python main_INIT_array_DEV.py    11
python main_INIT_array_DEV.py    12
python main_INIT_array_DEV.py    13
python main_INIT_array_DEV.py    14
python main_INIT_array_DEV.py    15
python main_INIT_array_DEV.py    16
python main_INIT_array_DEV.py    17
python main_INIT_array_DEV.py    18
python main_INIT_array_DEV.py    19
python main_INIT_array_DEV.py    20
python main_INIT_array_DEV.py    21
python main_INIT_array_DEV.py    22
python main_INIT_array_DEV.py    23
python main_INIT_array_DEV.py    24
python main_INIT_array_DEV.py    25
python main_INIT_array_DEV.py    26
python main_INIT_array_DEV.py    27
python main_INIT_array_DEV.py    28
python main_INIT_array_DEV.py    29
python main_INIT_array_DEV.py    30
python main_INIT_array_DEV.py    31
python main_INIT_array_DEV.py    32
python main_INIT_array_DEV.py    33
python main_INIT_array_DEV.py    34
python main_INIT_array_DEV.py    35
python main_INIT_array_DEV.py    36
python main_INIT_array_DEV.py    37
python main_INIT_array_DEV.py    38
python main_INIT_array_DEV.py    39
python main_INIT_array_DEV.py    40