python main_INIT_array_LRG.py     0
python main_INIT_array_LRG.py     1 
python main_INIT_array_LRG.py     2
python main_INIT_array_LRG.py     3
python main_INIT_array_LRG.py     4
python main_INIT_array_LRG.py     5
python main_INIT_array_LRG.py     6
python main_INIT_array_LRG.py     7
python main_INIT_array_LRG.py     8
python main_INIT_array_LRG.py     9
python main_INIT_array_LRG.py    10
python main_INIT_array_LRG.py    11
python main_INIT_array_LRG.py    12
python main_INIT_array_LRG.py    13
python main_INIT_array_LRG.py    14
python main_INIT_array_LRG.py    15
python main_INIT_array_LRG.py    16
python main_INIT_array_LRG.py    17
python main_INIT_array_LRG.py    18
python main_INIT_array_LRG.py    19
