python main_INIT_array_DEV.py     0
python main_INIT_array_DEV.py     1 
python main_INIT_array_DEV.py     2
python main_INIT_array_DEV.py     3
python main_INIT_array_DEV.py     4
python main_INIT_array_DEV.py     5
python main_INIT_array_DEV.py     6
python main_INIT_array_DEV.py     7
python main_INIT_array_DEV.py     8
python main_INIT_array_DEV.py     9
python main_INIT_array_DEV.py    10
python main_INIT_array_DEV.py    11
python main_INIT_array_DEV.py    12
python main_INIT_array_DEV.py    13
python main_INIT_array_DEV.py    14
python main_INIT_array_DEV.py    15
python main_INIT_array_DEV.py    16
python main_INIT_array_DEV.py    17
python main_INIT_array_DEV.py    18
python main_INIT_array_DEV.py    19
