python main_INIT_array_test.py     0
python main_INIT_array_test.py     1 
python main_INIT_array_test.py     2
python main_INIT_array_test.py     3
python main_INIT_array_test.py     4
python main_INIT_array_test.py     5
python main_INIT_array_test.py     6
python main_INIT_array_test.py     7
python main_INIT_array_test.py     8
python main_INIT_array_test.py     9
python main_INIT_array_test.py    10
python main_INIT_array_test.py    11
python main_INIT_array_test.py    12
python main_INIT_array_test.py    13
python main_INIT_array_test.py    14
python main_INIT_array_test.py    15
python main_INIT_array_test.py    16
python main_INIT_array_test.py    17
python main_INIT_array_test.py    18
python main_INIT_array_test.py    19
