python main_INIT_array_XLRG.py     0
python main_INIT_array_XLRG.py     1 
python main_INIT_array_XLRG.py     2
python main_INIT_array_XLRG.py     3
python main_INIT_array_XLRG.py     4
python main_INIT_array_XLRG.py     5
python main_INIT_array_XLRG.py     6
python main_INIT_array_XLRG.py     7
python main_INIT_array_XLRG.py     8
python main_INIT_array_XLRG.py     9
python main_INIT_array_XLRG.py    10
python main_INIT_array_XLRG.py    11
python main_INIT_array_XLRG.py    12
python main_INIT_array_XLRG.py    13
python main_INIT_array_XLRG.py    14
python main_INIT_array_XLRG.py    15
python main_INIT_array_XLRG.py    16
python main_INIT_array_XLRG.py    17
python main_INIT_array_XLRG.py    18
python main_INIT_array_XLRG.py    19
