python main_OPTIM_array_LRG.py   751
python main_OPTIM_array_LRG.py   700
python main_OPTIM_array_LRG.py   754
python main_OPTIM_array_LRG.py   524
python main_OPTIM_array_LRG.py   910
python main_OPTIM_array_LRG.py   940
python main_OPTIM_array_LRG.py   26
python main_OPTIM_array_LRG.py   912
python main_OPTIM_array_LRG.py   937
python main_OPTIM_array_LRG.py   8
python main_OPTIM_array_LRG.py   913
python main_OPTIM_array_LRG.py   928
python main_OPTIM_array_LRG.py   401
python main_OPTIM_array_LRG.py   10
python main_OPTIM_array_LRG.py   693
python main_OPTIM_array_LRG.py   905
python main_OPTIM_array_LRG.py   924
python main_OPTIM_array_LRG.py   724
python main_OPTIM_array_LRG.py   771
python main_OPTIM_array_LRG.py   525
python main_OPTIM_array_LRG.py   784
python main_OPTIM_array_LRG.py   757
python main_OPTIM_array_LRG.py   927
python main_OPTIM_array_LRG.py   911
python main_OPTIM_array_LRG.py   734
python main_OPTIM_array_LRG.py   743
python main_OPTIM_array_LRG.py   917
python main_OPTIM_array_LRG.py   399
python main_OPTIM_array_LRG.py   769
python main_OPTIM_array_LRG.py   699
python main_OPTIM_array_LRG.py   755
python main_OPTIM_array_LRG.py   930
python main_OPTIM_array_LRG.py   957
python main_OPTIM_array_LRG.py   698
python main_OPTIM_array_LRG.py   469
python main_OPTIM_array_LRG.py   756
python main_OPTIM_array_LRG.py   772
python main_OPTIM_array_LRG.py   943
python main_OPTIM_array_LRG.py   521
python main_OPTIM_array_LRG.py   904
python main_OPTIM_array_LRG.py   918
python main_OPTIM_array_LRG.py   17
python main_OPTIM_array_LRG.py   929
python main_OPTIM_array_LRG.py   789
python main_OPTIM_array_LRG.py   764
python main_OPTIM_array_LRG.py   770
python main_OPTIM_array_LRG.py   714
python main_OPTIM_array_LRG.py   518
python main_OPTIM_array_LRG.py   635
python main_OPTIM_array_LRG.py   19
python main_OPTIM_array_LRG.py   920
python main_OPTIM_array_LRG.py   932
python main_OPTIM_array_LRG.py   902
python main_OPTIM_array_LRG.py   915
python main_OPTIM_array_LRG.py   921
python main_OPTIM_array_LRG.py   552
python main_OPTIM_array_LRG.py   933
python main_OPTIM_array_LRG.py   530
python main_OPTIM_array_LRG.py   554
python main_OPTIM_array_LRG.py   520
python main_OPTIM_array_LRG.py   716
python main_OPTIM_array_LRG.py   903
python main_OPTIM_array_LRG.py   550
python main_OPTIM_array_LRG.py   783
python main_OPTIM_array_LRG.py   720
python main_OPTIM_array_LRG.py   24
python main_OPTIM_array_LRG.py   691
python main_OPTIM_array_LRG.py   470
python main_OPTIM_array_LRG.py   788
python main_OPTIM_array_LRG.py   313
python main_OPTIM_array_LRG.py   925
python main_OPTIM_array_LRG.py   5
python main_OPTIM_array_LRG.py   27
python main_OPTIM_array_LRG.py   553
python main_OPTIM_array_LRG.py   400
python main_OPTIM_array_LRG.py   919
python main_OPTIM_array_LRG.py   16
python main_OPTIM_array_LRG.py   32
python main_OPTIM_array_LRG.py   626
python main_OPTIM_array_LRG.py   6
python main_OPTIM_array_LRG.py   523
python main_OPTIM_array_LRG.py   806
python main_OPTIM_array_LRG.py   729
python main_OPTIM_array_LRG.py   694
python main_OPTIM_array_LRG.py   23
python main_OPTIM_array_LRG.py   389
python main_OPTIM_array_LRG.py   715
python main_OPTIM_array_LRG.py   923
python main_OPTIM_array_LRG.py   397
python main_OPTIM_array_LRG.py   934
python main_OPTIM_array_LRG.py   388
python main_OPTIM_array_LRG.py   468
python main_OPTIM_array_LRG.py   951
python main_OPTIM_array_LRG.py   474
python main_OPTIM_array_LRG.py   14
python main_OPTIM_array_LRG.py   22
python main_OPTIM_array_LRG.py   763
python main_OPTIM_array_LRG.py   637
python main_OPTIM_array_LRG.py   800
python main_OPTIM_array_LRG.py   808
python main_OPTIM_array_LRG.py   775
python main_OPTIM_array_LRG.py   549
python main_OPTIM_array_LRG.py   780
python main_OPTIM_array_LRG.py   4
python main_OPTIM_array_LRG.py   35
python main_OPTIM_array_LRG.py   726
python main_OPTIM_array_LRG.py   522
python main_OPTIM_array_LRG.py   409
python main_OPTIM_array_LRG.py   707
python main_OPTIM_array_LRG.py   519
python main_OPTIM_array_LRG.py   719
python main_OPTIM_array_LRG.py   688
python main_OPTIM_array_LRG.py   765
python main_OPTIM_array_LRG.py   9
python main_OPTIM_array_LRG.py   28
python main_OPTIM_array_LRG.py   950
python main_OPTIM_array_LRG.py   362
python main_OPTIM_array_LRG.py   753
python main_OPTIM_array_LRG.py   606
python main_OPTIM_array_LRG.py   37
python main_OPTIM_array_LRG.py   750
python main_OPTIM_array_LRG.py   368
python main_OPTIM_array_LRG.py   795
python main_OPTIM_array_LRG.py   528
python main_OPTIM_array_LRG.py   709
python main_OPTIM_array_LRG.py   710
python main_OPTIM_array_LRG.py   792
python main_OPTIM_array_LRG.py   752
python main_OPTIM_array_LRG.py   938
python main_OPTIM_array_LRG.py   29
python main_OPTIM_array_LRG.py   3
python main_OPTIM_array_LRG.py   804
python main_OPTIM_array_LRG.py   766
python main_OPTIM_array_LRG.py   692
python main_OPTIM_array_LRG.py   787
python main_OPTIM_array_LRG.py   777
python main_OPTIM_array_LRG.py   781
python main_OPTIM_array_LRG.py   39
python main_OPTIM_array_LRG.py   842
python main_OPTIM_array_LRG.py   604
python main_OPTIM_array_LRG.py   931
python main_OPTIM_array_LRG.py   151
python main_OPTIM_array_LRG.py   601
python main_OPTIM_array_LRG.py   418
python main_OPTIM_array_LRG.py   939
python main_OPTIM_array_LRG.py   778
python main_OPTIM_array_LRG.py   34
python main_OPTIM_array_LRG.py   796
python main_OPTIM_array_LRG.py   936
python main_OPTIM_array_LRG.py   1015
python main_OPTIM_array_LRG.py   721
python main_OPTIM_array_LRG.py   708
python main_OPTIM_array_LRG.py   531
python main_OPTIM_array_LRG.py   677
python main_OPTIM_array_LRG.py   774
python main_OPTIM_array_LRG.py   374
python main_OPTIM_array_LRG.py   366
python main_OPTIM_array_LRG.py   213
python main_OPTIM_array_LRG.py   36
python main_OPTIM_array_LRG.py   599
python main_OPTIM_array_LRG.py   154
python main_OPTIM_array_LRG.py   7
python main_OPTIM_array_LRG.py   21
python main_OPTIM_array_LRG.py   916
python main_OPTIM_array_LRG.py   44
python main_OPTIM_array_LRG.py   600
python main_OPTIM_array_LRG.py   1016
python main_OPTIM_array_LRG.py   415
python main_OPTIM_array_LRG.py   538
python main_OPTIM_array_LRG.py   475
python main_OPTIM_array_LRG.py   357
python main_OPTIM_array_LRG.py   713
python main_OPTIM_array_LRG.py   793
python main_OPTIM_array_LRG.py   379
python main_OPTIM_array_LRG.py   393
python main_OPTIM_array_LRG.py   598
python main_OPTIM_array_LRG.py   687
python main_OPTIM_array_LRG.py   767
python main_OPTIM_array_LRG.py   718
python main_OPTIM_array_LRG.py   786
python main_OPTIM_array_LRG.py   411
python main_OPTIM_array_LRG.py   536
python main_OPTIM_array_LRG.py   843
python main_OPTIM_array_LRG.py   634
python main_OPTIM_array_LRG.py   585
python main_OPTIM_array_LRG.py   636
python main_OPTIM_array_LRG.py   603
python main_OPTIM_array_LRG.py   608
python main_OPTIM_array_LRG.py   527
python main_OPTIM_array_LRG.py   408
python main_OPTIM_array_LRG.py   768
python main_OPTIM_array_LRG.py   514
python main_OPTIM_array_LRG.py   773
python main_OPTIM_array_LRG.py   703
python main_OPTIM_array_LRG.py   534
python main_OPTIM_array_LRG.py   805
python main_OPTIM_array_LRG.py   1166
python main_OPTIM_array_LRG.py   686
python main_OPTIM_array_LRG.py   211
python main_OPTIM_array_LRG.py   935
python main_OPTIM_array_LRG.py   587
python main_OPTIM_array_LRG.py   725
python main_OPTIM_array_LRG.py   705
python main_OPTIM_array_LRG.py   849
python main_OPTIM_array_LRG.py   359
python main_OPTIM_array_LRG.py   745
python main_OPTIM_array_LRG.py   680
python main_OPTIM_array_LRG.py   157
python main_OPTIM_array_LRG.py   46
python main_OPTIM_array_LRG.py   690
python main_OPTIM_array_LRG.py   420
python main_OPTIM_array_LRG.py   539
python main_OPTIM_array_LRG.py   38
python main_OPTIM_array_LRG.py   47
python main_OPTIM_array_LRG.py   674
python main_OPTIM_array_LRG.py   839
python main_OPTIM_array_LRG.py   717
python main_OPTIM_array_LRG.py   224
python main_OPTIM_array_LRG.py   416
python main_OPTIM_array_LRG.py   419
python main_OPTIM_array_LRG.py   706
python main_OPTIM_array_LRG.py   678
python main_OPTIM_array_LRG.py   629
python main_OPTIM_array_LRG.py   638
python main_OPTIM_array_LRG.py   631
python main_OPTIM_array_LRG.py   43
python main_OPTIM_array_LRG.py   730
python main_OPTIM_array_LRG.py   412
python main_OPTIM_array_LRG.py   378
python main_OPTIM_array_LRG.py   54
python main_OPTIM_array_LRG.py   48
python main_OPTIM_array_LRG.py   25
python main_OPTIM_array_LRG.py   701
python main_OPTIM_array_LRG.py   574
python main_OPTIM_array_LRG.py   840
python main_OPTIM_array_LRG.py   572
python main_OPTIM_array_LRG.py   414
python main_OPTIM_array_LRG.py   722
python main_OPTIM_array_LRG.py   402
python main_OPTIM_array_LRG.py   363
python main_OPTIM_array_LRG.py   471
python main_OPTIM_array_LRG.py   476
python main_OPTIM_array_LRG.py   733
python main_OPTIM_array_LRG.py   610
python main_OPTIM_array_LRG.py   40
python main_OPTIM_array_LRG.py   731
python main_OPTIM_array_LRG.py   53
python main_OPTIM_array_LRG.py   210
python main_OPTIM_array_LRG.py   535
python main_OPTIM_array_LRG.py   511
python main_OPTIM_array_LRG.py   358
python main_OPTIM_array_LRG.py   386
python main_OPTIM_array_LRG.py   704
python main_OPTIM_array_LRG.py   682
python main_OPTIM_array_LRG.py   394
python main_OPTIM_array_LRG.py   381
python main_OPTIM_array_LRG.py   841
python main_OPTIM_array_LRG.py   613
python main_OPTIM_array_LRG.py   811
python main_OPTIM_array_LRG.py   702
python main_OPTIM_array_LRG.py   949
python main_OPTIM_array_LRG.py   584
python main_OPTIM_array_LRG.py   947
python main_OPTIM_array_LRG.py   776
python main_OPTIM_array_LRG.py   537
python main_OPTIM_array_LRG.py   838
python main_OPTIM_array_LRG.py   684
python main_OPTIM_array_LRG.py   512
python main_OPTIM_array_LRG.py   589
python main_OPTIM_array_LRG.py   609
python main_OPTIM_array_LRG.py   785
python main_OPTIM_array_LRG.py   812
python main_OPTIM_array_LRG.py   1021
python main_OPTIM_array_LRG.py   472
python main_OPTIM_array_LRG.py   473
python main_OPTIM_array_LRG.py   962
python main_OPTIM_array_LRG.py   782
python main_OPTIM_array_LRG.py   605
python main_OPTIM_array_LRG.py   456
python main_OPTIM_array_LRG.py   847
python main_OPTIM_array_LRG.py   711
python main_OPTIM_array_LRG.py   607
python main_OPTIM_array_LRG.py   573
python main_OPTIM_array_LRG.py   727
python main_OPTIM_array_LRG.py   212
python main_OPTIM_array_LRG.py   588
python main_OPTIM_array_LRG.py   611
python main_OPTIM_array_LRG.py   744
python main_OPTIM_array_LRG.py   791
python main_OPTIM_array_LRG.py   413
python main_OPTIM_array_LRG.py   526
python main_OPTIM_array_LRG.py   396
python main_OPTIM_array_LRG.py   395
python main_OPTIM_array_LRG.py   226
python main_OPTIM_array_LRG.py   240
python main_OPTIM_array_LRG.py   41
python main_OPTIM_array_LRG.py   963
python main_OPTIM_array_LRG.py   45
python main_OPTIM_array_LRG.py   370
python main_OPTIM_array_LRG.py   627
python main_OPTIM_array_LRG.py   51
python main_OPTIM_array_LRG.py   513
python main_OPTIM_array_LRG.py   390
python main_OPTIM_array_LRG.py   417
python main_OPTIM_array_LRG.py   467
python main_OPTIM_array_LRG.py   540
python main_OPTIM_array_LRG.py   712
python main_OPTIM_array_LRG.py   364
python main_OPTIM_array_LRG.py   517
python main_OPTIM_array_LRG.py   242
python main_OPTIM_array_LRG.py   922
python main_OPTIM_array_LRG.py   398
python main_OPTIM_array_LRG.py   624
python main_OPTIM_array_LRG.py   616
python main_OPTIM_array_LRG.py   18
python main_OPTIM_array_LRG.py   239
python main_OPTIM_array_LRG.py   11
python main_OPTIM_array_LRG.py   617
python main_OPTIM_array_LRG.py   360
python main_OPTIM_array_LRG.py   941
python main_OPTIM_array_LRG.py   956
python main_OPTIM_array_LRG.py   886
python main_OPTIM_array_LRG.py   209
python main_OPTIM_array_LRG.py   515
python main_OPTIM_array_LRG.py   844
python main_OPTIM_array_LRG.py   356
python main_OPTIM_array_LRG.py   614
python main_OPTIM_array_LRG.py   529
python main_OPTIM_array_LRG.py   424
python main_OPTIM_array_LRG.py   369
python main_OPTIM_array_LRG.py   679
python main_OPTIM_array_LRG.py   425
python main_OPTIM_array_LRG.py   960
python main_OPTIM_array_LRG.py   807