python main_INIT_array_RUR.py     0
python main_INIT_array_RUR.py     1 
python main_INIT_array_RUR.py     2
python main_INIT_array_RUR.py     3
python main_INIT_array_RUR.py     4
python main_INIT_array_RUR.py     5
python main_INIT_array_RUR.py     6
python main_INIT_array_RUR.py     7
python main_INIT_array_RUR.py     8
python main_INIT_array_RUR.py     9
python main_INIT_array_RUR.py    10
python main_INIT_array_RUR.py    11
python main_INIT_array_RUR.py    12
python main_INIT_array_RUR.py    13
python main_INIT_array_RUR.py    14
python main_INIT_array_RUR.py    15
python main_INIT_array_RUR.py    16
python main_INIT_array_RUR.py    17
python main_INIT_array_RUR.py    18
python main_INIT_array_RUR.py    19
