python HPC_scenario_runs/main_INIT_array_DEV.py     0
python HPC_scenario_runs/main_INIT_array_DEV.py     1 
python HPC_scenario_runs/main_INIT_array_DEV.py     2
python HPC_scenario_runs/main_INIT_array_DEV.py     3
python HPC_scenario_runs/main_INIT_array_DEV.py     4
python HPC_scenario_runs/main_INIT_array_DEV.py     5
python HPC_scenario_runs/main_INIT_array_DEV.py     6
python HPC_scenario_runs/main_INIT_array_DEV.py     7
python HPC_scenario_runs/main_INIT_array_DEV.py     8
python HPC_scenario_runs/main_INIT_array_DEV.py     9
python HPC_scenario_runs/main_INIT_array_DEV.py    10
python HPC_scenario_runs/main_INIT_array_DEV.py    11
python HPC_scenario_runs/main_INIT_array_DEV.py    12
python HPC_scenario_runs/main_INIT_array_DEV.py    13
python HPC_scenario_runs/main_INIT_array_DEV.py    14
python HPC_scenario_runs/main_INIT_array_DEV.py    15
python HPC_scenario_runs/main_INIT_array_DEV.py    16
python HPC_scenario_runs/main_INIT_array_DEV.py    17
python HPC_scenario_runs/main_INIT_array_DEV.py    18
python HPC_scenario_runs/main_INIT_array_DEV.py    19
