python HPC_scenario_runs/main_INIT_array_LRG.py     0
python HPC_scenario_runs/main_INIT_array_LRG.py     1 
python HPC_scenario_runs/main_INIT_array_LRG.py     2
python HPC_scenario_runs/main_INIT_array_LRG.py     3
python HPC_scenario_runs/main_INIT_array_LRG.py     4
python HPC_scenario_runs/main_INIT_array_LRG.py     5
python HPC_scenario_runs/main_INIT_array_LRG.py     6
python HPC_scenario_runs/main_INIT_array_LRG.py     7
python HPC_scenario_runs/main_INIT_array_LRG.py     8
python HPC_scenario_runs/main_INIT_array_LRG.py     9
python HPC_scenario_runs/main_INIT_array_LRG.py    10
python HPC_scenario_runs/main_INIT_array_LRG.py    11
python HPC_scenario_runs/main_INIT_array_LRG.py    12
python HPC_scenario_runs/main_INIT_array_LRG.py    13
python HPC_scenario_runs/main_INIT_array_LRG.py    14
python HPC_scenario_runs/main_INIT_array_LRG.py    15
python HPC_scenario_runs/main_INIT_array_LRG.py    16
python HPC_scenario_runs/main_INIT_array_LRG.py    17
python HPC_scenario_runs/main_INIT_array_LRG.py    18
python HPC_scenario_runs/main_INIT_array_LRG.py    19
