python main_INIT_array_SUB.py     0
python main_INIT_array_SUB.py     1 
python main_INIT_array_SUB.py     2
python main_INIT_array_SUB.py     3
python main_INIT_array_SUB.py     4
python main_INIT_array_SUB.py     5
python main_INIT_array_SUB.py     6
python main_INIT_array_SUB.py     7
python main_INIT_array_SUB.py     8
python main_INIT_array_SUB.py     9
python main_INIT_array_SUB.py    10
python main_INIT_array_SUB.py    11
python main_INIT_array_SUB.py    12
python main_INIT_array_SUB.py    13
python main_INIT_array_SUB.py    14
python main_INIT_array_SUB.py    15
python main_INIT_array_SUB.py    16
python main_INIT_array_SUB.py    17
python main_INIT_array_SUB.py    18
python main_INIT_array_SUB.py    19
