python main_INIT_array.py     0
python main_INIT_array.py     1 
python main_INIT_array.py     2
python main_INIT_array.py     3
python main_INIT_array.py     4
python main_INIT_array.py     5
python main_INIT_array.py     6
python main_INIT_array.py     7
python main_INIT_array.py     8
python main_INIT_array.py     9
python main_INIT_array.py    10
python main_INIT_array.py    11
python main_INIT_array.py    12
python main_INIT_array.py    13
python main_INIT_array.py    14
python main_INIT_array.py    15
python main_INIT_array.py    16
python main_INIT_array.py    17
python main_INIT_array.py    18
python main_INIT_array.py    19
